// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lexfkgyimtpdevqpscpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxleGZrZ3lpbXRwZGV2cXBzY3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDQwNTIsImV4cCI6MjA2Njc4MDA1Mn0.g8RbiAcPI_BUMdTVeUQa9kJscDuyURgBmDOmrYUCtoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);